name: 'Artifacts Cleanup'
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
    
  schedule:
  - cron: '0 * * * *' # UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: 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
          expire-in: 30 minutes
