name: Deploy CYC WS
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
        
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      - name: Restore Packages
        run: nuget restore "Job Scheduling.sln"
      
      - name: Create Build Directory
        run: mkdir _build  

      - name: Build
        working-directory:  ./
        run: dotnet build "Job Scheduling.sln" /t:Rebuild /p:configuration="Release" /p:outdir="../_build"
          
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: cyc_ws
          path: ${{ github.workspace }}/_build/**/*
          
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: cyc_ws
      - name: Deploy to IIS
        run: |
          iisreset /stop
          Copy-Item _build/* C:\inetpub\wwwroot\cyc\ws -Recurse -Force
          iisreset /start
  
    
        
